### ISSUE TITLE
The trouble with linear indexing...

### ISSUE THREAD

**Issue by mbauman** [mbauman/RaggedArrays.jl#3]
Cartesian indexing of ragged structures is really hard and slow, so it's really nice to support linear indexing for the contiguous `RaggedArray` and use it for `eachindex`.  The trouble is that Base algorithms assume that if the size is the same, then linear indexes across two arrays refer to the same location.  This isn't true for RaggedArrays:

``` jl
julia> R1 = RaggedArray(Vector{Int}[[1],[1,1],[2,2,3]])
??x3 RaggedArrays.RaggedArray{Int64,2,1,1}:
   1       1     2
 #undef    1     2
 #undef  #undef  3

julia> R2 = RaggedArray(Vector{Int}[[1,1,1],[2,2],[3]])
??x3 RaggedArrays.RaggedArray{Int64,2,1,1}:
 1    2       3
 1    2     #undef
 1  #undef  #undef

julia> R1==R2
true
```

I think the only proper solution here would be to return the array of ragged lengths within `size` or to drop `AbstractArray` support entirely.

**Comment by mauro3** [comment]
Sparse arrays face a bit of the same problem, although there the unused indices are not `#undef` but `0`.  Thus many Base functions need to be specialized (for performance), e.g. `==`.

Anyways, couldn't this be solved in general, if Julia wouldn't transform the `end` into `size`, `endof` or `trainlingsize` but instead left that transformation to the getindex function?  Instead a general slicing object could be used, as e.g. in Python.
